services:
  - name: docker:18.09.7-dind
    alias: docker

stages:
  - build
  - docker

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:3.6.0-jdk-13
  script:
    - mvn $MAVEN_CLI_OPTS package

docker:
  stage: docker
  image: docker:18.09.7
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --rm -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master